services:
  active09-dev-app:
    container_name: active09-dev-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - active09-dev-db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=active09-dev-db
      - DB_PORT=3306
      - DB_DATABASE=active09_db
      - DB_USERNAME=active09_user
      - DB_PASSWORD=active09_password
    ports:
      - "8080:80"

  active09-dev-db:
    container_name: active09-dev-db
    image: mysql:8
    restart: always
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: active09_db
      MYSQL_USER: active09_user
      MYSQL_PASSWORD: active09_password
    volumes:
      - ./db_data:/var/lib/mysql
