services:
  active09-prod-app:
    container_name: active09-prod-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - active09-prod-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=active09-prod-db
      - DB_PORT=3306
      - DB_DATABASE=active09_prod_db
      - DB_USERNAME=active09_prod_db
      - DB_PASSWORD=70f8893a82ea937e6edba1465b9437d53aa473d
    expose:
      - "80"
    networks:
      - nginx_proxy
      - active09_prod_internal

  active09-prod-db:
    container_name: active09-prod-db
    image: mysql:8
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 70f8893a82ea937e6edba1465b9437d53aa473dcda03c83fc96387aece80dcd1
      MYSQL_DATABASE: active09_prod_db
      MYSQL_USER: active09_prod_db
      MYSQL_PASSWORD: 70f8893a82ea937e6edba1465b9437d53aa473d
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - active09_prod_internal

volumes:
  active09_prod_db_data:
    external: true
    name: active09_prod_db_data

networks:
  nginx_proxy:
    external: true
  active09_prod_internal:
    name: active09_prod_internal
    driver: bridge
